# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
# This re-usable component makes artifacts

name: artifacts-component

on:
  workflow_call:

permissions:
  contents: write

jobs:

  build-artifact:
    # https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts
    # https://github.com/marketplace/actions/upload-a-build-artifact
    name: artifacts-component
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5 # needed for cache
        with:
          go-version: stable
          cache: true
      - name: build
        run: make build
      - name: Copy Files
        run: |
          mkdir artifacts
          cp timeaway artifacts/timeaway-linux-amd64
      - name: archive
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: artifacts/
          if-no-files-found: error
          retention-days: 5
          overwrite: true
